#!/bin/bash
# This script can be used to install and configure Consul on a server so that the server automatically joins or forms
# a cluster during boot. This script has been tested with the following operating systems:
#
# 1. Ubuntu 16.04
# 1. Amazon Linux

set -e

readonly DEFAULT_INSTALL_PATH="/opt/consul"
readonly DEFAULT_CONSUL_USER="consul"

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

readonly COLOR_INFO='\033[0;32m'
readonly COLOR_ERROR='\033[0;31m'
readonly COLOR_END='\033[0m'

function print_usage {
  echo
  echo "Usage: install-consul [OPTIONS]"
  echo
  echo "This script can be used to install and configure Consul on a server so that the server automatically joins or forms a cluster during boot. This script has been tested with Ubuntu 16.04 and Amazon Linux."
  echo
  echo "Options:"
  echo
  echo -e "  --version\t\tThe version of Consul to install. Required."
  echo -e "  --path\t\tThe path where Consul should be installed. Optional. Default: $DEFAULT_INSTALL_PATH."
  echo -e "  --user\t\tThe user who will own the Consul install directories. Optional. Default: $DEFAULT_CONSUL_USER."
  echo
  echo "Example:"
  echo
  echo "  install-consul --version 0.7.5"
}

function log {
  local readonly level="$1"
  local readonly color="$2"
  local readonly message="$3"
  local readonly timestamp=$(date +"%Y-%m-%d %H:%M:%S")
  echo -e "${color}${timestamp} [${level}] [install-consul] ${message}${COLOR_END}"
}

function log_info {
  local readonly message="$1"
  log "INFO" "$COLOR_INFO" "$message"
}

function log_error {
  local readonly message="$1"
  log "ERROR" "$COLOR_ERROR" "$message"
}

function assert_not_empty {
  local readonly arg_name="$1"
  local readonly arg_value="$2"

  if [[ -z "$arg_value" ]]; then
    log_error "The value for '$arg_name' cannot be empty"
    print_usage
    exit 1
  fi
}

# Install steps are based on: http://unix.stackexchange.com/a/291098/215969
function install_supervisord_debian {
  sudo apt install -y supervisor
  sudo update-rc.d supervisor defaults
  sudo systemctl enable supervisor
}

# Install steps are based on: http://stackoverflow.com/a/31576473/483528
function install_supervisord_amazon_linux {
  sudo pip install supervisor
  echo_supervisord_conf | sudo tee /etc/supervisord.conf > /dev/null
  sudo cp "$SCRIPT_DIR/supervisor-initd-script.sh" "/etc/init.d/supervisor"
  sudo chmod a+x /etc/init.d/supervisor
  sudo chkconfig --add supervisor
  sudo chkconfig supervisor on
}

function has_yum {
  [ -n "$(command -v yum)" ]
}

function has_apt {
  [ -n "$(command -v apt)" ]
}

function install_dependencies {
  log_info "Installing dependencies"

  if $(has_apt); then
    sudo apt install -y wget unzip
    install_supervisord_debian
  elif $(has_yum); then
    sudo yum install -y wget unzip
    install_supervisord_amazon_linux
  else
    log_error "Could not find apt or yum. Cannot install dependencies on this OS."
    exit 1
  fi
}

function user_exists {
  local readonly username="$1"
  id "$username" >/dev/null 2>&1
}

function create_consul_user {
  local readonly username="$1"

  if $(user_exists "$username"); then
    echo "User $username already exists. Will not create again."
  else
    log_info "Creating user named $username"
    sudo useradd "$username"
  fi
}

function create_consul_install_paths {
  local readonly path="$1"
  local readonly username="$2"

  log_info "Creating install dirs for Consul at $path"
  sudo mkdir -p "$path"
  sudo mkdir -p "$path/bin"
  sudo mkdir -p "$path/config"
  sudo mkdir -p "$path/data"

  log_info "Changing ownership of $path to $username"
  sudo chown -R "$username:$username" "$path"
}

function install_binaries {
  local readonly version="$1"
  local readonly path="$2"
  local readonly username="$3"

  local readonly url="https://releases.hashicorp.com/consul/${version}/consul_${version}_linux_amd64.zip"
  local readonly download_path="/tmp/consul_${version}_linux_amd64.zip"
  local readonly bin_dir="$path/bin"
  local readonly consul_dest_path="$bin_dir/consul"
  local readonly run_consul_dest_path="$bin_dir/run-consul"

  log_info "Downloading Consul version $version from $url to $download_path"
  wget -O "$download_path" "$url"
  unzip -d /tmp "$download_path"

  log_info "Moving Consul binary to $consul_dest_path"
  sudo mv "/tmp/consul" "$consul_dest_path"
  sudo chmod a+x "$consul_dest_path"

  log_info "Copying Consul run script to $run_consul_dest_path"
  sudo mv "$SCRIPT_DIR/run-consul" "$run_consul_dest_path"
  sudo chmod a+x "$run_consul_dest_path"
}

function install {
  local version=""
  local path="$DEFAULT_INSTALL_PATH"
  local user="$DEFAULT_CONSUL_USER"

  while [[ $# > 0 ]]; do
    local key="$1"

    case "$key" in
      --version)
        version="$2"
        shift
        ;;
      --path)
        path="$2"
        shift
        ;;
      --user)
        user="$2"
        shift
        ;;
      --help)
        print_usage
        exit
        ;;
      *)
        log_error "Unrecognized argument: $key"
        print_usage
        exit 1
        ;;
    esac

    shift
  done

  assert_not_empty "--version" "$version"
  assert_not_empty "--path" "$path"
  assert_not_empty "--user" "$user"

  install_dependencies
  create_consul_user "$user"
  create_consul_install_paths "$path" "$user"
  install_binaries "$version" "$path" "$user"
}

install "$@"